import globals from 'globals'
import eslint from '@eslint/js'
import tseslint from 'typescript-eslint'
import { defineConfig } from 'eslint/config'

/** @type {import('eslint').Linter.Config[]} */
export default defineConfig(
  {
    ignores: ['dist/**/*', '*.config.*', 'scripts/**/*', 'migrations/**/*'],
  },
  {
    files: ['**/*.ts'],
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
    rules: {
      semi: 'off',
      'prefer-const': 'error',
      'no-unused-vars': 'off',
      'consistent-return': 'off',
      'default-param-last': 'off',
      'dot-notation': 'off',
      'id-length': [2, { exceptions: ['_', 'x', 'y', 'i', 'j', 'id'], properties: 'never' }],
      'init-declarations': 'off',
      'no-array-constructor': 'off',
      'no-empty-function': 'off',
      'no-implied-eval': 'off',
      'no-loop-func': 'off',
      'no-magic-numbers': 'off',
      'no-shadow': 'off',
    },
  },
  eslint.configs.recommended,
  tseslint.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parser: tseslint.parser,
      globals: {
        ...globals.node,
      },
      parserOptions: {
        project: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/array-type': [
        'error',
        {
          default: 'array-simple',
          readonly: 'array-simple',
        },
      ],
      '@typescript-eslint/await-thenable': ['error'],
      '@typescript-eslint/ban-ts-comment': ['error'],
      '@typescript-eslint/ban-tslint-comment': ['error'],
      '@typescript-eslint/consistent-generic-constructors': ['error', 'type-annotation'],
      '@typescript-eslint/consistent-indexed-object-style': ['error', 'record'],
      '@typescript-eslint/consistent-return': [
        'error',
        {
          treatUndefinedAsUnspecified: true,
        },
      ],
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        {
          assertionStyle: 'as',
        },
      ],
      '@typescript-eslint/consistent-type-definitions': ['warn', 'interface'],
      '@typescript-eslint/consistent-type-exports': [
        'error',
        {
          fixMixedExportsWithInlineTypeSpecifier: true,
        },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        {
          disallowTypeAnnotations: true,
          fixStyle: 'separate-type-imports',
          prefer: 'type-imports',
        },
      ],
      '@typescript-eslint/default-param-last': ['error'],
      '@typescript-eslint/dot-notation': [
        'error',
        {
          allowKeywords: true,
        },
      ],
      '@typescript-eslint/explicit-function-return-type': ['off'],
      '@typescript-eslint/explicit-module-boundary-types': ['off'],
      '@typescript-eslint/init-declarations': ['error', 'always'],
      '@typescript-eslint/method-signature-style': ['error', 'property'],
      '@typescript-eslint/no-array-constructor': ['error'],
      '@typescript-eslint/no-array-delete': ['error'],
      '@typescript-eslint/no-base-to-string': ['error'],
      '@typescript-eslint/no-confusing-non-null-assertion': ['error'],
      '@typescript-eslint/no-confusing-void-expression': ['error'],
      '@typescript-eslint/no-deprecated': ['error'],
      '@typescript-eslint/no-duplicate-enum-values': ['error'],
      '@typescript-eslint/no-duplicate-type-constituents': ['error'],
      '@typescript-eslint/no-dynamic-delete': ['error'],
      '@typescript-eslint/no-empty-function': ['error'],
      '@typescript-eslint/no-empty-interface': ['off'],
      '@typescript-eslint/no-empty-object-type': ['off'],
      '@typescript-eslint/no-explicit-any': [
        'error',
        {
          fixToUnknown: true,
        },
      ],
      '@typescript-eslint/no-extra-non-null-assertion': ['error'],
      '@typescript-eslint/no-floating-promises': [
        'error',
        {
          checkThenables: true,
          ignoreIIFE: true,
          ignoreVoid: true,
        },
      ],
      '@typescript-eslint/no-for-in-array': ['error'],
      '@typescript-eslint/no-implied-eval': ['error'],
      '@typescript-eslint/no-inferrable-types': ['error'],
      '@typescript-eslint/no-loop-func': ['error'],
      '@typescript-eslint/no-meaningless-void-operator': ['error'],
      '@typescript-eslint/no-misused-promises': ['off'],
      '@typescript-eslint/no-misused-spread': ['error'],
      '@typescript-eslint/no-mixed-enums': ['error'],
      '@typescript-eslint/no-non-null-asserted-nullish-coalescing': ['error'],
      '@typescript-eslint/no-non-null-asserted-optional-chain': ['error'],
      '@typescript-eslint/no-non-null-assertion': ['error'],
      '@typescript-eslint/no-redundant-type-constituents': ['error'],
      '@typescript-eslint/no-require-imports': ['error'],
      '@typescript-eslint/no-shadow': [
        'error',
        {
          ignoreOnInitialization: true,
        },
      ],
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': ['error'],
      '@typescript-eslint/no-unnecessary-condition': ['error'],
      '@typescript-eslint/no-unnecessary-parameter-property-assignment': ['error'],
      '@typescript-eslint/no-unnecessary-qualifier': ['error'],
      '@typescript-eslint/no-unnecessary-template-expression': ['error'],
      '@typescript-eslint/no-unnecessary-type-arguments': ['error'],
      '@typescript-eslint/no-unnecessary-type-assertion': ['error'],
      '@typescript-eslint/no-unnecessary-type-constraint': ['error'],

      // TODO:
      // '@typescript-eslint/no-unsafe-argument': ['error'],
      // '@typescript-eslint/no-unsafe-assignment': ['error'],
      // '@typescript-eslint/no-unsafe-call': ['error'],
      // '@typescript-eslint/no-unsafe-declaration-merging' : ['error'],
      // '@typescript-eslint/no-unsafe-enum-comparison' : ['error'],
      // '@typescript-eslint/no-unsafe-function-type' : ['error'],
      // '@typescript-eslint/no-unsafe-member-access' : ['error'],
      // '@typescript-eslint/no-unsafe-return' : ['error'],
      // '@typescript-eslint/no-unsafe-type-assertion' : ['error'],
      // '@typescript-eslint/no-unsafe-unary-minus' : ['error'],
      // '@typescript-eslint/no-unused-expressions' : ['error'],
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          args: 'all',
          argsIgnorePattern: '^_',
          caughtErrors: 'all',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],
      // '@typescript-eslint/no-use-before-define' : ['error'],
      // '@typescript-eslint/no-useless-constructor' : ['error'],
      // '@typescript-eslint/no-useless-empty-export' : ['error'],
      // '@typescript-eslint/no-var-requires' : ['error'],
      // '@typescript-eslint/no-wrapper-object-types' : ['error'],
      // '@typescript-eslint/non-nullable-type-assertion-style' : ['error'],
      // '@typescript-eslint/only-throw-error' : ['error'],
      // '@typescript-eslint/parameter-properties' : ['error'],
      // '@typescript-eslint/prefer-as-const' : ['error'],
      // '@typescript-eslint/prefer-destructuring' : ['error'],
      // '@typescript-eslint/prefer-enum-initializers' : ['error'],
      // '@typescript-eslint/prefer-find' : ['error'],
      // '@typescript-eslint/prefer-for-of' : ['error'],
      // '@typescript-eslint/prefer-function-type' : ['error'],
      // '@typescript-eslint/prefer-includes' : ['error'],
      // '@typescript-eslint/prefer-literal-enum-member' : ['error'],
      // '@typescript-eslint/prefer-namespace-keyword' : ['error'],
      // '@typescript-eslint/prefer-nullish-coalescing' : ['error'],
      // '@typescript-eslint/prefer-optional-chain' : ['error'],
      // '@typescript-eslint/prefer-promise-reject-errors' : ['error'],
      // '@typescript-eslint/prefer-readonly' : ['error'],
      // '@typescript-eslint/prefer-readonly-parameter-types' : ['error'],
      // '@typescript-eslint/prefer-reduce-type-parameter' : ['error'],
      // '@typescript-eslint/prefer-regexp-exec' : ['error'],
      // '@typescript-eslint/prefer-return-this-type' : ['error'],
      // '@typescript-eslint/prefer-string-starts-ends-with' : ['error'],
      // '@typescript-eslint/prefer-ts-expect-error' : ['error'],
      // '@typescript-eslint/promise-function-async' : ['error'],
      // '@typescript-eslint/related-getter-setter-pairs' : ['error'],
      // '@typescript-eslint/require-array-sort-compare' : ['error'],
      // '@typescript-eslint/require-await' : ['error'],
      // '@typescript-eslint/restrict-plus-operands' : ['error'],
      // '@typescript-eslint/restrict-template-expressions' : ['error'],
      // '@typescript-eslint/return-await' : ['error'],
      // '@typescript-eslint/sort-type-constituents' : ['error'],
      // '@typescript-eslint/strict-boolean-expressions' : ['error'],
      // '@typescript-eslint/switch-exhaustiveness-check' : ['error'],
      // '@typescript-eslint/triple-slash-reference' : ['error'],
      // '@typescript-eslint/typedef' : ['error'],
      // '@typescript-eslint/unbound-method' : ['error'],
      // '@typescript-eslint/unified-signatures' : ['error'],
      // '@typescript-eslint/use-unknown-in-catch-callback-variable' : ['error'],
    },
  },
)
