process.env['DATABASE_URL'] = 'postgresql://test:test@localhost:5432/test_db'
process.env['JWT_ACCESS_SECRET'] = 'test-jwt-secret-minimum-32-characters-long'
process.env['REDIS_URL'] = 'redis://localhost:6379'
process.env['NODE_ENV'] = 'test'
process.env['ALLOWED_ORIGINS'] = 'http://localhost:3000'
